.TH "FlingTests/src/EngineCoreTests.cpp" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingTests/src/EngineCoreTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'catch2/catch\&.hpp'\fP
.br
\fC#include 'pch\&.h'\fP
.br
\fC#include 'Engine\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Smoke test', '[core]')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Smoke test', ''[core])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
