.TH "Fling::SwapChainSupportDetails" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::SwapChainSupportDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkSurfaceCapabilitiesKHR \fBCapabilities\fP"
.br
.ti -1c
.RI "std::vector< VkSurfaceFormatKHR > \fBFormats\fP"
.br
.ti -1c
.RI "std::vector< VkPresentModeKHR > \fBPresentModes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "VkSurfaceCapabilitiesKHR Fling::SwapChainSupportDetails::Capabilities"

.SS "std::vector<VkSurfaceFormatKHR> Fling::SwapChainSupportDetails::Formats"

.SS "std::vector<VkPresentModeKHR> Fling::SwapChainSupportDetails::PresentModes"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
