.TH "FlingEngine/Resources/inc/FlingConfig.h" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Resources/inc/FlingConfig.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Singleton\&.hpp'\fP
.br
\fC#include 'INIReader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFling::FlingConfig\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFling\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
