.TH "FlingEngine/Utils/inc/FlingTypes.h" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Utils/inc/FlingTypes.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <inttypes\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBUINT8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBUINT16\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBUINT32\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBUINT64\fP"
.br
.ti -1c
.RI "typedef int8_t \fBINT8\fP"
.br
.ti -1c
.RI "typedef signed short \fBINT16\fP"
.br
.ti -1c
.RI "typedef int32_t \fBINT32\fP"
.br
.ti -1c
.RI "typedef int64_t \fBINT64\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBINT16\fP"

.SS "typedef int32_t \fBINT32\fP"

.SS "typedef int64_t \fBINT64\fP"

.SS "typedef int8_t \fBINT8\fP"

.SS "typedef unsigned short \fBUINT16\fP"

.SS "typedef uint32_t \fBUINT32\fP"

.SS "typedef uint64_t \fBUINT64\fP"

.SS "typedef uint8_t \fBUINT8\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
