.TH "Fling::FlingConfig" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::FlingConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlingConfig\&.h>\fP
.PP
Inherits \fBFling::Singleton< FlingConfig >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP () override"
.br
.ti -1c
.RI "virtual void \fBShutdown\fP () override"
.br
.ti -1c
.RI "bool \fBLoadConfigFile\fP (const std::string &t_File)"
.br
.ti -1c
.RI "std::string \fBGetString\fP (const std::string &t_Section, const std::string &t_Key)"
.br
.ti -1c
.RI "int \fBGetInt\fP (const std::string &t_Section, const std::string &t_Key)"
.br
.ti -1c
.RI "bool \fBGetBool\fP (const std::string &t_Section, const std::string &t_Key)"
.br
.ti -1c
.RI "float \fBGetFloat\fP (const std::string &t_Section, const std::string &t_Key)"
.br
.ti -1c
.RI "double \fBGetDouble\fP (const std::string &t_Section, const std::string &t_Key)"
.br
.ti -1c
.RI "\fBUINT32\fP \fBLoadCommandLineOpts\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static INIReader \fBm_IniReader\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provide simple access to engine configuration options from an INI file #TODO Parse command line options as well 
.SH "Member Function Documentation"
.PP 
.SS "bool Fling::FlingConfig::GetBool (const std::string & t_Section, const std::string & t_Key)"

.SS "double Fling::FlingConfig::GetDouble (const std::string & t_Section, const std::string & t_Key)"

.SS "float Fling::FlingConfig::GetFloat (const std::string & t_Section, const std::string & t_Key)"

.SS "int Fling::FlingConfig::GetInt (const std::string & t_Section, const std::string & t_Key)"

.SS "std::string Fling::FlingConfig::GetString (const std::string & t_Section, const std::string & t_Key)"

.SS "void Fling::FlingConfig::Init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBFling::Singleton< FlingConfig >\fP\&.
.SS "\fBUINT32\fP Fling::FlingConfig::LoadCommandLineOpts (int argc, char * argv[])"
Load in the command line options and store them somewhere that is globally accessible
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Argument count 
.br
\fIargv\fP Command line args 
.RE
.PP
\fBReturns:\fP
.RS 4
Number of options loaded 
.RE
.PP

.SS "bool Fling::FlingConfig::LoadConfigFile (const std::string & t_File)"
Attempt to load a config file (\&.ini) for the engine
.PP
\fBParameters:\fP
.RS 4
\fIt_File\fP File path to the config file
.RE
.PP
\fBReturns:\fP
.RS 4
True if file was read successfully 
.RE
.PP

.SS "void Fling::FlingConfig::Shutdown ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBFling::Singleton< FlingConfig >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "INIReader Fling::FlingConfig::m_IniReader\fC [static]\fP, \fC [private]\fP"
Ini config file reader 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
