.TH "Fling::Timing" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::Timing
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timing\&.h>\fP
.PP
Inherits \fBFling::Singleton< Timing >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP () override"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Update the time values of the timer\&. Should be done at the beginning of every frame "
.ti -1c
.RI "float \fBGetDeltaTime\fP () const"
.br
.ti -1c
.RI "double \fBGetTime\fP () const"
.br
.ti -1c
.RI "float \fBGetTimef\fP () const"
.br
.RI "Get float "
.ti -1c
.RI "float \fBGetFrameStartTime\fP () const"
.br
.ti -1c
.RI "double \fBGetStartTime\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_deltaTime\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBUINT64\fP \fBm_deltaTick\fP = 0"
.br
.ti -1c
.RI "double \fBm_lastFrameStartTime\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBm_frameStartTimef\fP = 0\&.0f"
.br
.ti -1c
.RI "double \fBm_perfCountDuration\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBm_startTime\fP = 0\&.0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "float Fling::Timing::GetDeltaTime () const\fC [inline]\fP"

.SS "float Fling::Timing::GetFrameStartTime () const\fC [inline]\fP"

.SS "double Fling::Timing::GetStartTime () const\fC [inline]\fP"

.SS "double Fling::Timing::GetTime () const"

.SS "float Fling::Timing::GetTimef () const\fC [inline]\fP"

.PP
Get float 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void Fling::Timing::Init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBFling::Singleton< Timing >\fP\&.
.SS "void Fling::Timing::Update ()"

.PP
Update the time values of the timer\&. Should be done at the beginning of every frame 
.SH "Member Data Documentation"
.PP 
.SS "\fBUINT64\fP Fling::Timing::m_deltaTick = 0\fC [private]\fP"

.SS "float Fling::Timing::m_deltaTime = 0\&.0f\fC [private]\fP"

.SS "float Fling::Timing::m_frameStartTimef = 0\&.0f\fC [private]\fP"

.SS "double Fling::Timing::m_lastFrameStartTime = 0\&.0\fC [private]\fP"

.SS "double Fling::Timing::m_perfCountDuration = 0\&.0\fC [private]\fP"

.SS "double Fling::Timing::m_startTime = 0\&.0\fC [private]\fP"
The time that the program started 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
