.TH "Fling::QueueFamilyIndices" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::QueueFamilyIndices \- Used to keep track of what properties a given queue satisfies  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsComplete\fP () const"
.br
.RI "Determines if this "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUINT32\fP \fBGraphicsFamily\fP = 0"
.br
.ti -1c
.RI "\fBUINT32\fP \fBPresentFamily\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to keep track of what properties a given queue satisfies 


.SH "Member Function Documentation"
.PP 
.SS "bool Fling::QueueFamilyIndices::IsComplete () const\fC [inline]\fP"

.PP
Determines if this 
.PP
\fBReturns:\fP
.RS 4
True if queue family is complete
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBUINT32\fP Fling::QueueFamilyIndices::GraphicsFamily = 0"

.SS "\fBUINT32\fP Fling::QueueFamilyIndices::PresentFamily = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
