.TH "Fling::Engine" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::Engine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Engine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEngine\fP ()"
.br
.ti -1c
.RI "\fBEngine\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "\fB~Engine\fP ()"
.br
.ti -1c
.RI "\fBUINT64\fP \fBRun\fP ()"
.br
.RI "Run the engine "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBStartup\fP ()"
.br
.RI "Start any systems or subsystems that may be needed "
.ti -1c
.RI "virtual void \fBTick\fP ()"
.br
.RI "Initial tick for the engine frame "
.ti -1c
.RI "virtual void \fBShutdown\fP ()"
.br
.RI "Shutdown all engine systems and do any necessary cleanup "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_CmdLineArgCount\fP = 0"
.br
.ti -1c
.RI "char ** \fBm_CmdLineArgs\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fling::Engine::Engine ()"

.SS "Fling::Engine::Engine (int argc, char * argv[])"

.SS "Fling::Engine::~Engine ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBUINT64\fP Fling::Engine::Run ()"

.PP
Run the engine 
.PP
\fBReturns:\fP
.RS 4
Error code or 0 for success
.RE
.PP

.SS "void Fling::Engine::Shutdown ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Shutdown all engine systems and do any necessary cleanup 
.SS "void Fling::Engine::Startup ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Start any systems or subsystems that may be needed 
.SS "void Fling::Engine::Tick ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Initial tick for the engine frame 
.SH "Member Data Documentation"
.PP 
.SS "int Fling::Engine::m_CmdLineArgCount = 0\fC [private]\fP"

.SS "char** Fling::Engine::m_CmdLineArgs = nullptr\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
