.TH "Fling::Vertex" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vertex\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static VkVertexInputBindingDescription \fBGetBindingDescription\fP ()"
.br
.ti -1c
.RI "static std::array< VkVertexInputAttributeDescription, 2 > \fBGetAttributeDescriptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec2 \fBPos\fP"
.br
.ti -1c
.RI "glm::vec3 \fBColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic \fBVertex\fP outline for use with our vertex buffers 
.SH "Member Function Documentation"
.PP 
.SS "static std::array<VkVertexInputAttributeDescription, 2> Fling::Vertex::GetAttributeDescriptions ()\fC [inline]\fP, \fC [static]\fP"

.SS "static VkVertexInputBindingDescription Fling::Vertex::GetBindingDescription ()\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Fling::Vertex::Color"

.SS "glm::vec2 Fling::Vertex::Pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
