.TH "Fling::Random" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fling::Random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Random\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBInit\fP ()"
.br
.RI "Initialize the random number generator "
.ti -1c
.RI "static const int \fBRandom0ToN\fP (const int t_max)"
.br
.RI "Get a random int between 0 and the max "
.ti -1c
.RI "static const int \fBRandomBetween\fP (const int t_min, const int t_max)"
.br
.RI "Generate a random number between the two given values "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBbIsInitalized\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Fling::Random::Init ()\fC [static]\fP"

.PP
Initialize the random number generator 
.PP
\fBReturns:\fP
.RS 4
True if successful
.RE
.PP

.SS "const int Fling::Random::Random0ToN (const int t_max)\fC [static]\fP"

.PP
Get a random int between 0 and the max 
.PP
\fBParameters:\fP
.RS 4
\fIt_max\fP Max number to generate to
.RE
.PP
\fBReturns:\fP
.RS 4
Number between 0 and the given
.RE
.PP

.SS "const int Fling::Random::RandomBetween (const int t_min, const int t_max)\fC [static]\fP"

.PP
Generate a random number between the two given values 
.PP
\fBParameters:\fP
.RS 4
\fIt_min\fP Min number to gerneate between
.br
\fIt_max\fP Max number to generate between
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRandom\fP int between the two values
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "bool Fling::Random::bIsInitalized = false\fC [static]\fP"
Flag to determine if random has been initialized 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
