.TH "FlingEngine/Utils/inc/pch.h" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Utils/inc/pch.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <map>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <set>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'FlingTypes\&.h'\fP
.br
\fC#include 'Random\&.h'\fP
.br
\fC#include 'Logger\&.h'\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <glm/vec4\&.hpp>\fP
.br
\fC#include <glm/mat4x4\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_ENABLE_LOGGING\fP"
.br
.ti -1c
.RI "#define \fBF_INLINE\fP   inline"
.br
.ti -1c
.RI "#define \fBGLFW_INCLUDE_VULKAN\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_DEPTH_ZERO_TO_ONE\fP"
.br
.ti -1c
.RI "#define \fBFLING_DEFAULT_WINDOW_WIDTH\fP   800"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_ENABLE_LOGGING"

.SS "#define F_INLINE   inline"

.SS "#define FLING_DEFAULT_WINDOW_WIDTH   800"

.SS "#define GLFW_INCLUDE_VULKAN"

.SS "#define GLM_FORCE_DEPTH_ZERO_TO_ONE"

.SS "#define GLM_FORCE_RADIANS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
