.TH "FlingEngine/Utils/inc/Random.h" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Utils/inc/Random.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFling::Random\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFling\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
