.TH "FlingTests/src/RendererTests.cpp" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingTests/src/RendererTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'catch2/catch\&.hpp'\fP
.br
\fC#include 'pch\&.h'\fP
.br
\fC#include 'Renderer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Renderer', '[Renderer]')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Renderer', ''[Renderer])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
