.TH "FlingEngine/Graphics/inc/Renderer.h" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Graphics/inc/Renderer.h
.SH SYNOPSIS
.br
.PP
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include 'Singleton\&.hpp'\fP
.br
\fC#include 'Vertex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFling::QueueFamilyIndices\fP"
.br
.RI "Used to keep track of what properties a given queue satisfies "
.ti -1c
.RI "struct \fBFling::SwapChainSupportDetails\fP"
.br
.ti -1c
.RI "class \fBFling::Renderer\fP"
.br
.RI "Core renderer for the application "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFling\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_INCLUDE_VULKAN\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::vector< Vertex > \fBFling::Temp_Vertices\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_INCLUDE_VULKAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
