.TH "FlingEngine/Utils/src/Timing.cpp" 3 "Fri Jul 19 2019" "Version 0.00.1" "Fling Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlingEngine/Utils/src/Timing.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Timing\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFling\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::chrono::high_resolution_clock::time_point \fBFling::sStartTime\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fling Engine from the source code\&.
